---
driver:
  name: ec2

driver_config:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID'] %>
  region: us-east-1
  # availability_zone:
  # subnet_id:
  # security_group_ids:

provisioner:
  name: chef_zero

platforms:
  - name: amazon-2014.09
    driver_plugin: ec2
    driver_config:
      image_id: ami-9a6ed3f2 #ami-b66ed3de
      username: ec2-user
      ssh_key: <%= ENV['AWS_SSH_KEY_PATH'] %>

suites:
  - name: server
    run_list:
      - recipe[mysql_community::server]
  - name: client
    run_list:
      - recipe[mysql_community::client]
