---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-6.6

suites:
  - name: server
    run_list:
      - recipe[mysql_community::server]
    attributes:
      mysqld:
        root_password: ilikerandompasswords
  - name: client
    run_list:
      - recipe[mysql_community::client]
