AllCops:
  Include:
    - '**/Berksfile'
    - Gemfile
    - Rakefile
    - Thorfile
    - Guardfile
  Exclude:
    - vendor/**/*

Style/Documentation:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Metrics/LineLength:
  Max: 90

# Metrics/MethodLength:
#   Max: 20

#inherit_from: .rubocop_todo.yml
