name             'mysql_community'
maintainer       'Brian Clark'
maintainer_email 'brian@clark.zone'
license          'apache2'
description      'Installs/Configures MySQL'
long_description 'Installs/Configures MySQL'
version          '0.1.1'

depends 'yum-mysql-community', '~> 0.1'
depends 'mysqld', '~> 1.0.3'
